version: "3"
services:
  github-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-service
    ports:
      - "${GITHUB_SERVICE_PORT}:${GITHUB_SERVICE_PORT}"
    environment:
      - GITHUB_SERVICE_PORT=${GITHUB_SERVICE_PORT}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - directus-network
  directus:
    container_name: directus-service
    image: directus/directus:11.3.5
    ports:
      - 8056:8055
    volumes:
      - directus_volume:/directus/uploads
      - directus_volume:/directus/extensions
    env_file:
      - .env
    environment:
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: "pg"
      DB_HOST: ${POSTGRES_URL}
      DB_PORT: "8093"
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "*"
      CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      CORS_ALLOWED_HEADERS: "*"
      CORS_EXPOSED_HEADERS: "*"
    networks:
      - directus-network

volumes:
  directus_volume:
  database_volume:
  
networks:
  directus-network:
    driver: bridge