version: "3"
services:
  directus:
    container_name: directus-service
    image: directus/directus:11.3.5
    ports:
      - 8056:8055
    volumes:
      - directus_volume:/directus/uploads
      - directus_volume:/directus/extensions
    depends_on:
      database:
        condition: service_healthy 
   
    environment:
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

     

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

volumes:
  directus_volume:
  database_volume: