POST http://localhost:8055/items/contact
Content-Type: application/json
Authorization: Bearer B5grPPGm31KZTLApAXcojojdAzv_EReT

{
  "name": "Tiago Luiz Pole",
  "phoneNumber": "(11) 99999-9999",
  "email": "tiagoluizpoli@gmail.com", 
  "message": "Hello World!",
  "solution": "backend"
}

###

GET https://directus.lunalabs.com.br/items/home?fields=*,translations.*,translations.directus_translations_id.*
Content-Type: application/json
Authorization: Bearer u9oOauzKFqUvpPriGGsPlWjLc3q9XyY7

###

GET https://directus.lunalabs.com.br/translations
Content-Type: application/json
Authorization: Bearer u9oOauzKFqUvpPriGGsPlWjLc3q9XyY7





###

GET https://api.telegram.org/bot7483784514:AAEGvD5nNLzNj55phTCXOlEQ32E_cI48GKA/getUpdates